# Generated by Django 5.2.6 on 2025-09-12 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Car",
            fields=[
                ("id_car", models.AutoField(primary_key=True, serialize=False)),
                ("license_plate", models.CharField(max_length=15)),
                ("model", models.CharField(max_length=20)),
                ("color", models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="CarOwner",
            fields=[
                ("id_owner", models.AutoField(primary_key=True, serialize=False)),
                ("first_name", models.CharField(max_length=30)),
                ("last_name", models.CharField(max_length=30)),
                ("birth_date", models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="DrivingLicense",
            fields=[
                ("id_license", models.AutoField(primary_key=True, serialize=False)),
                ("license_number", models.CharField(max_length=10)),
                (
                    "license_type",
                    models.CharField(
                        choices=[
                            ("A", "Категория A"),
                            ("B", "Категория B"),
                            ("C", "Категория C"),
                            ("D", "Категория D"),
                            ("BE", "Категория BE"),
                            ("CE", "Категория CE"),
                            ("DE", "Категория DE"),
                            ("Tm", "Категория Tm"),
                            ("Tb", "Категория Tb"),
                            ("M", "Категория M"),
                            ("A1", "Подкатегория A1"),
                            ("B1", "Подкатегория B1"),
                            ("C1", "Подкатегория C1"),
                            ("D1", "Подкатегория D1"),
                            ("C1E", "Подкатегория C1E"),
                            ("D1E", "Подкатегория D1E"),
                        ],
                        max_length=10,
                    ),
                ),
                ("issue_date", models.DateField()),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="project_first_app.carowner",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Ownership",
            fields=[
                ("id_ownership", models.AutoField(primary_key=True, serialize=False)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "car",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="project_first_app.car",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="project_first_app.carowner",
                    ),
                ),
            ],
        ),
    ]
