# Generated by Django 5.2.6 on 2025-09-19 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project_first_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="owner",
            name="address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="owner",
            name="nationality",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="owner",
            name="passport_number",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
