# Generated by Django 5.2.6 on 2025-09-15 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("project_first_app", "0002_carowner_cars"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="CarOwner",
            new_name="Owner",
        ),
    ]
