# Generated by Django 5.2.6 on 2025-09-16 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("project_first_app", "0003_rename_carowner_owner"),
    ]

    operations = [
        migrations.RenameField(
            model_name="car",
            old_name="id_car",
            new_name="car_id",
        ),
        migrations.RenameField(
            model_name="drivinglicense",
            old_name="id_license",
            new_name="license_id",
        ),
        migrations.RenameField(
            model_name="owner",
            old_name="id_owner",
            new_name="owner_id",
        ),
        migrations.RenameField(
            model_name="ownership",
            old_name="id_ownership",
            new_name="ownership_id",
        ),
    ]
